- name: Настройка Prometheus Server для мониторинга node_exporter
  hosts: prometheus-servers
  become: true
  vars_files:
    - group_vars/prometheus/vars.yml

  tasks:
    - name: Считать текущий prometheus.yml
      ansible.builtin.slurp:
        src: "{{ prometheus_config_path }}"
      register: prometheus_config_raw

    - name: Распарсить prometheus.yml
      set_fact:
        prometheus_config_content: "{{ prometheus_config_raw.content | b64decode }}"

    - name: Debug node_exporters_targets
      debug:
        var: node_exporters_targets

    - name: Обновить конфигурацию prometheus для node_exporter
      ansible.builtin.template:
        src: prometheus.yml.j2
        dest: "{{ prometheus_config_path }}"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_user }}"
        mode: '0644'
      notify:
        - restart prometheus

    - name: Enable and start Prometheus service
      ansible.builtin.systemd:
        name: prometheus
        enabled: true
        state: started

  handlers:
    - name: restart prometheus
      ansible.builtin.systemd:
        name: prometheus
        state: restarted
