---
- hosts: prometheus-servers
  become: true
  vars_files:
    - group_vars/prometheus/vars.yml

  tasks:
    - name: Create prometheus group
      ansible.builtin.group:
        name: "{{ prometheus_group }}"
        system: true
        state: present

    - name: Create prometheus user and group
      ansible.builtin.user:
        name: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        system: true
        create_home: false
        shell: /sbin/nologin
      register: user_created

    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: '0755'
      loop:
        - "{{ prometheus_install_dir }}"
        - "{{ prometheus_data_dir }}"

    - name: Download Prometheus archive
      ansible.builtin.get_url:
        url: "{{ prometheus_download_url }}"
        dest: "/tmp/prometheus-{{ prometheus_version }}.tar.gz"
        mode: '0644'

    - name: Extract Prometheus archive
      ansible.builtin.unarchive:
        src: "/tmp/prometheus-{{ prometheus_version }}.tar.gz"
        dest: "{{ prometheus_install_dir }}"
        remote_src: true
        creates: "{{ prometheus_install_dir }}/prometheus-{{ prometheus_version }}.linux-amd64/prometheus"

    - name: Symlink prometheus binaries
      ansible.builtin.file:
        src: "{{ prometheus_install_dir }}/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        state: link
        force: true
      loop:
        - prometheus
        - promtool

    - name: Set ownership of install directory
      ansible.builtin.file:
        path: "{{ prometheus_install_dir }}"
        state: directory
        recurse: true
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"

    - name: Create Prometheus systemd service file
      ansible.builtin.copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus Monitoring
          Wants=network-online.target
          After=network-online.target

          [Service]
          User={{ prometheus_user }}
          Group={{ prometheus_group }}
          Type=simple
          ExecStart=/usr/local/bin/prometheus \
            --config.file={{ prometheus_install_dir }}/prometheus-{{ prometheus_version }}.linux-amd64/prometheus.yml \
            --storage.tsdb.path={{ prometheus_data_dir }}

          Restart=always

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable and start Prometheus service
      ansible.builtin.systemd:
        name: prometheus
        enabled: true
        state: started